# NpuEmbeddings -- generate the Unicode tables the C++ WordPiece tokenizer needs.
# SPDX-License-Identifier: Apache-2.0
#
# WHY GENERATE INSTEAD OF LINKING ICU
# -----------------------------------
# BERT's BasicTokenizer is defined in terms of Python's `unicodedata`:
# lowercasing, NFD decomposition with Mn (nonspacing mark) removal, and the
# Unicode punctuation/control/space categories. Reimplementing those by hand is
# how tokenizers quietly diverge on the 1% of text that is not ASCII; linking
# ICU drags a large dependency into a runtime whose whole point is that it is
# small and self-contained.
#
# So: do it the way this project does everything else -- compute it offline in
# Python (build-time Python is explicitly allowed, CLAUDE.md rule 5) and emit a
# static C++ table. The tables are then EXACTLY what HuggingFace would compute,
# by construction rather than by careful reading.
#
# WHAT IS FOLDED INTO ONE LOOKUP
# ------------------------------
# `fold` maps a codepoint to the result of `lower()` followed by NFD-with-Mn-
# dropped -- both of BasicTokenizer's per-character transforms in one table.
# Entries equal to the identity are omitted, so the table only holds the ~5k
# codepoints that actually change.
#
# The one context-dependent case Python has is Greek capital sigma, which
# lowercases to the final form at the end of a word. That cannot live in a
# per-codepoint table, so it is emitted as a constant and handled in the C++.
#
# Env: any Python 3 (no NPU, no torch).
# Usage:
#   python tools\gen_tokenizer_tables.py

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "runtime" / "include" / "bert_unicode_tables.hpp"

MAX_CP = 0x110000
SIGMA = 0x03A3          # GREEK CAPITAL LETTER SIGMA


def fold_one(cp: int) -> list[int]:
    """lower() then strip_accents(), exactly as BasicTokenizer applies them."""
    ch = chr(cp)
    low = ch.lower()
    nfd = unicodedata.normalize("NFD", low)
    return [ord(c) for c in nfd if unicodedata.category(c) != "Mn"]


def is_punct(cp: int) -> bool:
    if 33 <= cp <= 47 or 58 <= cp <= 64 or 91 <= cp <= 96 or 123 <= cp <= 126:
        return True
    return unicodedata.category(chr(cp)).startswith("P")


def is_control(cp: int) -> bool:
    ch = chr(cp)
    if ch in ("\t", "\n", "\r"):
        return False
    return unicodedata.category(ch).startswith("C")


def is_space(cp: int) -> bool:
    ch = chr(cp)
    if ch in (" ", "\t", "\n", "\r"):
        return True
    return unicodedata.category(ch) == "Zs"


def ranges(pred) -> list[tuple[int, int]]:
    """Compress a predicate over all codepoints into inclusive ranges."""
    out, start = [], None
    for cp in range(MAX_CP):
        if 0xD800 <= cp <= 0xDFFF:          # surrogates: never valid scalars
            continue
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CP - 1))
    return out


def main() -> int:
    # --- fold table -------------------------------------------------------
    folds = {}
    for cp in range(MAX_CP):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        f = fold_one(cp)
        if f != [cp]:
            folds[cp] = f
    keys = sorted(folds)

    # Flat storage: each entry points at (offset, length) into one array, so
    # the multi-codepoint results (and the empty ones -- combining marks fold
    # to nothing) need no special case.
    flat, index = [], []
    for cp in keys:
        index.append((cp, len(flat), len(folds[cp])))
        flat.extend(folds[cp])

    punct = ranges(is_punct)
    ctrl = ranges(is_control)
    space = ranges(is_space)

    def emit_ranges(name, rs):
        body = ",\n    ".join(
            ", ".join(f"{{0x{a:X}, 0x{b:X}}}" for a, b in rs[i:i + 4])
            for i in range(0, len(rs), 4))
        return (f"inline constexpr CpRange {name}[] = {{\n    {body}\n}};\n"
                f"inline constexpr int {name}_n = {len(rs)};\n")

    lines = [
        "//===- bert_unicode_tables.hpp ------------------------------*- C++ -*-===//",
        "//",
        "// GENERATED by tools/gen_tokenizer_tables.py -- DO NOT EDIT.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// The Unicode facts BERT's BasicTokenizer is defined in terms of, computed",
        f"// from Python {sys.version.split()[0]}'s unicodedata (UCD "
        f"{unicodedata.unidata_version}) so the C++ agrees with HuggingFace by",
        "// construction rather than by careful reading.",
        "//",
        f"//   fold      {len(keys)} codepoints whose lower()+NFD-drop-Mn differs",
        f"//   punct     {len(punct)} ranges",
        f"//   control   {len(ctrl)} ranges",
        f"//   space     {len(space)} ranges",
        "",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace bert_uni {",
        "",
        f'inline constexpr const char *kUnicodeVersion = "{unicodedata.unidata_version}";',
        f"inline constexpr uint32_t kGreekCapitalSigma = 0x{SIGMA:X};",
        "inline constexpr uint32_t kGreekSmallSigma = 0x3C3;",
        "inline constexpr uint32_t kGreekFinalSigma = 0x3C2;",
        "",
        "struct CpRange { uint32_t lo, hi; };",
        "struct FoldEntry { uint32_t cp; uint32_t off; uint32_t len; };",
        "",
    ]

    body = ",\n    ".join(
        ", ".join(f"0x{c:X}" for c in flat[i:i + 12])
        for i in range(0, len(flat), 12))
    lines.append(f"inline constexpr uint32_t kFoldData[] = {{\n    {body}\n}};")
    lines.append(f"inline constexpr int kFoldData_n = {len(flat)};\n")

    body = ",\n    ".join(
        ", ".join(f"{{0x{cp:X},{off},{ln}}}" for cp, off, ln in index[i:i + 6])
        for i in range(0, len(index), 6))
    lines.append(f"inline constexpr FoldEntry kFold[] = {{\n    {body}\n}};")
    lines.append(f"inline constexpr int kFold_n = {len(index)};\n")

    lines.append(emit_ranges("kPunct", punct))
    lines.append(emit_ranges("kControl", ctrl))
    lines.append(emit_ranges("kSpace", space))
    lines.append("}  // namespace bert_uni")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(REPO)}  ({kb:.1f} KB)")
    print(f"  UCD {unicodedata.unidata_version}")
    print(f"  fold entries {len(index)}, fold data {len(flat)}")
    print(f"  punct ranges {len(punct)}, control {len(ctrl)}, space {len(space)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
